FROM ubuntu:18.04

RUN apt-get update && apt-get install --no-install-recommends -y python3 \
 python3-distutils \
 wget && \
 apt-get autoclean && rm -rf /var/lib/apt/lists/* && \
 update-alternatives --install /usr/bin/python python /usr/bin/python3 10

# install MUSCLE
WORKDIR /usr/local/bin
RUN wget https://drive5.com/muscle/downloads3.8.31/muscle3.8.31_i86linux64.tar.gz --no-check-certificate && \
  tar -xzvf muscle3.8.31_i86linux64.tar.gz && \
  rm -r muscle3.8.31_i86linux64.tar.gz && \
  mkdir muscle3.8 && \
  mv muscle3.8.31_i86linux64 muscle3.8/muscle

ENV PATH="/usr/local/bin/muscle3.8/:${PATH}"

# install prank
WORKDIR /usr/local/bin
RUN wget http://wasabiapp.org/download/prank/prank.linux64.170427.tgz && \
  tar -xzvf prank.linux64.170427.tgz && \
  rm -r prank.linux64.170427.tgz

ENV PATH="/usr/local/bin/prank/bin:${PATH}"

WORKDIR /data

